### ISSUE TITLE
Install whithout composer

### ISSUE THREAD

**Issue by sagudev** [mimmi20/BrowserDetector#69]
Can you write tutorial how to install without composer. I want to be portable. Please help me!

**Comment by mimmi20** [comment]
This library has too much dependencies. For this reason, composer is required.

**Comment by mimmi20** [comment]
Do you have support for Phar archives?

**Comment by sagudev** [comment]
Yes, I have it. But I want to have it portble for https://github.com/php-admin/php-admin
I want to php-admin be download&run whithout using any other thinks

**Comment by sagudev** [comment]
Or maybe I can install it with composer and then it will be portable. But it wil still use composer autorun.

**Comment by mimmi20** [comment]
If you want download it ready to run, you need a phar archive, but I never built one before.

**Comment by mimmi20** [comment]
Just include the project wont work without composer. Why dont you want to use composer? By the way, why did you include other projects (phpmyadmin) into your own?

**Comment by sagudev** [comment]
bacause this is php based manager that has phpmyadmin and pimp my log to help you manage db and logs

**Comment by sagudev** [comment]
> If you want download it ready to run, you need a phar archive, but I never built one before.

how can i buid it?

It will make your project portable?

**Comment by sagudev** [comment]
ok i did not use your project in phpadmin i use original browscap-php with composer. Thanks for trying to help me.
